name: API-SERVER CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: npm install

      - name: Test Unit
        run: npm run test

      - name: e2e Test
        run: npm run test:e2e

      - name: Nest Build
        uses: npm run build
